### ISSUE TITLE
script to update contributors does not work

### ISSUE THREAD

**Issue by EgbertRijke** [UniMath/agda-unimath#663]
I get the following error:

```
egbertrijke@MacBook-Pro-3 scripts % python update_contributors.py 
  File "update_contributors.py", line 9
    url = f'https://api.github.com/repos/{repo}/contributors'
                                                            ^
SyntaxError: invalid syntax
```

**Comment by EgbertRijke** [comment]
Alas, if I run it with python 3.11 I still get an error:

```
egbertrijke@MacBook-Pro-3 scripts % python3.11 update_contributors.py 
Traceback (most recent call last):
  File "/Users/egbertrijke/Repositories/agda-unimath/scripts/update_contributors.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

**Comment by VojtechStep** [comment]
I'm pretty sure different Python versions don't share the same installed dependencies, so you'll want to do `python3.11 -m pip install -r scripts/requirements.txt`. That should install the required dependencies for Python 3.11.

**Comment by EgbertRijke** [comment]
That worked. Many thanks!
